name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        ocaml-compiler:
          - 4.14
          - 5.2
          - 5.3
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          opam-pin: false
          opam-depext: false
          ocaml-compiler: ${{ matrix.ocaml-compiler }}


      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      - run: |
          opam install . --with-dev-setup --with-test --deps-only
          opam exec -- dune build @fmt
